/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpus.view;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import perpus.db.KoneksiDatabase;

/**
 *
 * @author hp
 */
public class ViewListDataAnggota extends javax.swing.JFrame {

    /**
     * Creates new form ViewListDataAnggota
     */
    private ViewPeminjaman vP;
    private DefaultTableModel model;
    private String sql="";
    public ViewListDataAnggota(ViewPeminjaman vP) {
        initComponents();
        
        this.vP = vP;
        model = new DefaultTableModel();
        viewListDataAnggota.setModel(model);
        model.addColumn("Id Anggota");
        model.addColumn("Nama Anggota");
        model.addColumn("No HP");
        model.addColumn("Jenis Kelamin");
        model.addColumn("Alamat");
        tampilDataAnggota("");
    }
    
    private void tampilDataAnggota(String data){
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        
        if(data.equals("")){
            sql = "Select * from anggota";
        } else sql = "select * from anggota where namaAnggota LIKE'"+data+"%'";
        
        try {
            Statement stat = (Statement) KoneksiDatabase.getKoneksi().createStatement();
            ResultSet res = stat.executeQuery(sql);
            
            while(res.next()){
                //mengambil hasil query variable sql
                Object[] hasil;
                hasil = new Object[5];//karena ada 6 field di table
                hasil[0] = res.getString("idAnggota");
                hasil[1] = res.getString("namaAnggota");
                hasil[2] = res.getString("noTelp");
                hasil[3] = res.getString("jenisKelamin");
                hasil[4] = res.getString("alamat");
                
                model.addRow(hasil);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(ViewAnggotaInternal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        viewListDataAnggota = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cariNamaAnggota = new javax.swing.JTextField();
        batalCari = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));

        viewListDataAnggota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        viewListDataAnggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewListDataAnggotaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(viewListDataAnggota);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Data Anggota");

        jLabel3.setText("Cari Nama Anggota");

        cariNamaAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariNamaAnggotaActionPerformed(evt);
            }
        });
        cariNamaAnggota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cariNamaAnggotaKeyPressed(evt);
            }
        });

        batalCari.setBackground(new java.awt.Color(255, 153, 153));
        batalCari.setText("Batal");
        batalCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalCariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(216, 216, 216)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(cariNamaAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(batalCari, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cariNamaAnggota)
                    .addComponent(jLabel3)
                    .addComponent(batalCari))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewListDataAnggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewListDataAnggotaMouseClicked
        // TODO add your handling code here:
        int listX = viewListDataAnggota.getSelectedRow();
        vP.getIdAnggotaTxt().setText(viewListDataAnggota.getValueAt(listX,0).toString());
        vP.getNamaAnggotaTxt().setText(viewListDataAnggota.getValueAt(listX,1).toString());
        vP.getNoTelpTxt().setText(viewListDataAnggota.getValueAt(listX,2).toString());
        vP.getJenisKelaminTxt().setText(viewListDataAnggota.getValueAt(listX,3).toString());
        vP.getAlamatTxt().setText(viewListDataAnggota.getValueAt(listX,4).toString());
        
        this.dispose();
    }//GEN-LAST:event_viewListDataAnggotaMouseClicked

    private void cariNamaAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariNamaAnggotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cariNamaAnggotaActionPerformed

    private void cariNamaAnggotaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cariNamaAnggotaKeyPressed
        // TODO add your handling code here:
        tampilDataAnggota(cariNamaAnggota.getText());
    }//GEN-LAST:event_cariNamaAnggotaKeyPressed

    private void batalCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalCariActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_batalCariActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batalCari;
    private javax.swing.JTextField cariNamaAnggota;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable viewListDataAnggota;
    // End of variables declaration//GEN-END:variables
}
