/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpus.view;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import perpus.db.KoneksiDatabase;

/**
 *
 * @author hp
 */
public class ViewListDataBuku extends javax.swing.JFrame {

    /**
     * Creates new form ViewListDataBuku
     */
    private ViewPeminjaman vP;
    private DefaultTableModel model;
    private String sql="";
    public ViewListDataBuku(ViewPeminjaman vP) {
        initComponents();
        this.vP = vP;
        model = new DefaultTableModel();
        viewListDataBuku.setModel(model);
        model.addColumn("Id Buku");
        model.addColumn("Judul Buku");
        model.addColumn("Pengarang");
        model.addColumn("Penerbit");
        model.addColumn("Tahun");
        model.addColumn("Stok");
        tampilDataBuku("");
    }

    private void tampilDataBuku(String data){
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        
        if(data.equals("")){
            sql = "Select * from buku";
        } else sql = "select * from buku where judulBuku LIKE'"+data+"%'";
        
        try {
            Statement stat = (Statement) KoneksiDatabase.getKoneksi().createStatement();
            ResultSet res = stat.executeQuery(sql);
            
            while(res.next()){
                //mengambil hasil query variable sql
                Object[] hasil;
                hasil = new Object[6];//karena ada 6 field di table
                hasil[0] = res.getString("idBuku");
                hasil[1] = res.getString("judulBuku");
                hasil[2] = res.getString("pengarang");
                hasil[3] = res.getString("penerbit");
                hasil[4] = res.getString("tahun");
                hasil[5] = res.getString("stok");
                
                model.addRow(hasil);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(ViewAnggotaInternal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cariNamaBuku = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        viewListDataBuku = new javax.swing.JTable();
        batalCari = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Data Buku");

        jLabel2.setText("Cari Nama Buku");

        cariNamaBuku.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cariNamaBukuKeyPressed(evt);
            }
        });

        viewListDataBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        viewListDataBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewListDataBukuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(viewListDataBuku);

        batalCari.setBackground(new java.awt.Color(255, 153, 153));
        batalCari.setText("Batal");
        batalCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalCariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cariNamaBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(batalCari, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cariNamaBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(batalCari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewListDataBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewListDataBukuMouseClicked
        // TODO add your handling code here:
        int listX = viewListDataBuku.getSelectedRow();
        vP.getIdBukuTxt().setText(viewListDataBuku.getValueAt(listX,0).toString());
        vP.getJudulBukuTxt().setText(viewListDataBuku.getValueAt(listX,1).toString());
        
        dispose();
    }//GEN-LAST:event_viewListDataBukuMouseClicked

    private void batalCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalCariActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_batalCariActionPerformed

    private void cariNamaBukuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cariNamaBukuKeyPressed
        // TODO add your handling code here:
        tampilDataBuku(cariNamaBuku.getText());
    }//GEN-LAST:event_cariNamaBukuKeyPressed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batalCari;
    private javax.swing.JTextField cariNamaBuku;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable viewListDataBuku;
    // End of variables declaration//GEN-END:variables
}
