/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpus.view;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import perpus.db.KoneksiDatabase;

/**
 *
 * @author hp
 */
public class ViewListDataPeminjaman extends javax.swing.JFrame {

    /**
     * Creates new form ViewListDataPeminjaman
     */
    private ViewPengembalian vPP;
    private DefaultTableModel model;
    private String sql="";
    public ViewListDataPeminjaman(ViewPengembalian vPP) {
        initComponents();
        this.vPP = vPP;
        model = new DefaultTableModel();
        viewListDataPeminjaman.setModel(model);
        model.addColumn("Id Peminjaman");
        model.addColumn("Id Anggota");
        model.addColumn("Id Buku");
        model.addColumn("Nama Anggota");
        model.addColumn("Judul Buku");
        model.addColumn("Tanggal Pinjam");
        model.addColumn("Jumlah");
        model.addColumn("Status Pinjam");
        tampilDataPeminjaman("");
    }
    
    private void tampilDataPeminjaman(String data){
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        
        if(data.equals("")){
            sql = "Select peminjaman.idPeminjaman, peminjaman.idAnggota, peminjaman.idBuku, anggota.namaAnggota, buku.judulBuku, peminjaman.tglPinjam, jumlah, statusPinjam FROM peminjaman "
                    + "JOIN buku ON peminjaman.idBuku = buku.idBuku "
                    + "JOIN anggota ON peminjaman.idAnggota = anggota.idAnggota"
                    + " where statusPinjam = 'dipinjam'";
        } else sql = "Select peminjaman.idPeminjaman, peminjaman.idAnggota, peminjaman.idBuku, anggota.namaAnggota, buku.judulBuku, peminjaman.tglPinjam, jumlah, statusPinjam FROM peminjaman "
                    + "JOIN buku ON peminjaman.idBuku = buku.idBuku "
                    + "JOIN anggota ON peminjaman.idAnggota = anggota.idAnggota"
                    + " where idPeminjaman LIKE'"+data+"%'";
        
        try {
            Statement stat = (Statement) KoneksiDatabase.getKoneksi().createStatement();
            ResultSet res = stat.executeQuery(sql);
            
            while(res.next()){
                //mengambil hasil query variable sql
                Object[] hasil;
                hasil = new Object[8];//karena ada 6 field di table
                hasil[0] = res.getString("idPeminjaman");
                hasil[1] = res.getString("idAnggota");
                hasil[2] = res.getString("idBuku");
                hasil[3] = res.getString("namaAnggota");
                hasil[4] = res.getString("judulBuku");
                hasil[5] = res.getString("tglPinjam");
                hasil[6] = res.getString("jumlah");
                hasil[7] = res.getString("statusPinjam");
                
                model.addRow(hasil);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(ViewAnggotaInternal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cariIdPeminjaman = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        viewListDataPeminjaman = new javax.swing.JTable();
        batalCari = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Data Peminjaman");

        jLabel2.setText("Cari ID Peminjaman");

        cariIdPeminjaman.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cariIdPeminjamanKeyPressed(evt);
            }
        });

        viewListDataPeminjaman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        viewListDataPeminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewListDataPeminjamanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(viewListDataPeminjaman);

        batalCari.setBackground(new java.awt.Color(255, 153, 153));
        batalCari.setText("Batal");
        batalCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalCariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cariIdPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(batalCari, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(159, 159, 159)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cariIdPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addComponent(batalCari, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewListDataPeminjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewListDataPeminjamanMouseClicked
        // TODO add your handling code here:
        int listX = viewListDataPeminjaman.getSelectedRow();
        vPP.getIdPeminjamanTxt().setText(viewListDataPeminjaman.getValueAt(listX,0).toString());
        vPP.getIdAnggotaTxt().setText(viewListDataPeminjaman.getValueAt(listX,1).toString());
        vPP.getIdBukuTxt().setText(viewListDataPeminjaman.getValueAt(listX,2).toString());
        vPP.getNamaAnggotaTxt().setText(viewListDataPeminjaman.getValueAt(listX,3).toString());
        vPP.getJudulBukuTxt().setText(viewListDataPeminjaman.getValueAt(listX,4).toString());
        vPP.getTglBukuTxt().setText(viewListDataPeminjaman.getValueAt(listX,5).toString());
        vPP.getJumlahTxt().setText(viewListDataPeminjaman.getValueAt(listX,6).toString());
        
        dispose();
    }//GEN-LAST:event_viewListDataPeminjamanMouseClicked

    private void batalCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalCariActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_batalCariActionPerformed

    private void cariIdPeminjamanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cariIdPeminjamanKeyPressed
        // TODO add your handling code here:
        tampilDataPeminjaman(cariIdPeminjaman.getText());
    }//GEN-LAST:event_cariIdPeminjamanKeyPressed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batalCari;
    private javax.swing.JTextField cariIdPeminjaman;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable viewListDataPeminjaman;
    // End of variables declaration//GEN-END:variables
}
